### ISSUE TITLE
Loan process

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#181]
# UI

UX presented here: https://docs.google.com/presentation/d/1eCTxSe2yML3xb3y5c9uS8zm3GdotJymJIZ-6NrfrpZg/edit#slide=id.g2375b13bec5_0_2

We would also add a `Loans` resource.  This would show in the left-hand menu.  The `List` would include these columns:
- created
- Holder
- Items Outstanding (calculated count)

The `Show` component is described in the above UI

# Logic:
I _guess_ we would implement this logic in the DataProvider.  We would add this new method:

```
loanItems => (items: Array<Item['id'], recipient: User['id'], by: User['id'], remarks: string): void
returnItems => (items: Array<Item['id'], by: User['id']): void
```

The method would perform the following steps:

## New loan
- create new `Loan` element
- create new `Loan Item` elements

## Return
- mark  `Loan Item` elements with `returnedDate`
- if all `Loan Item` elements for a `Loan` have been returned, mark `Loan` as returned

### Return process

- a user wishes to return a number of items
- the admin opens LoanList, and filters for loans for that user
- admin selects the relevant loan, viewed in LoanShow
- switch to `Loan Items` tab, which displays `LoanItemList`
- filters for `Items on loan`
- admin selects items being returned, then clicks on `Return`

# Data
```
Loan:
  - id: integer
  - createdAt: string
  - holder:  User['id']
  - loanedBy:  User['id']
  - remarks: string
 
LoanItem:
   - id: integer
   - createdAt: string
   - item: Item['id']
   - loan: Loan['id']
   - receivedBy: User['id']
   - returnedDate: string | null  // (null if still on loan)
   - remarks: string
```
